/*
 *  This file is automatically generated by css-module-type-definitions
 */

export type Keys = 'box' | 'description' | 'primary' | 'root' | 'secondary' | 'spinnerContainer' | 'todo';
export type css = { [key in Keys]: string };

declare const css: css;
export default css;
