export { BrickMaze } from './brick-maze.ts';
export { CircularMaze } from './circular-maze.ts';
export { CubicMaze } from './cubic-maze.ts';
export { HexagonMaze } from './hexagon-maze.ts';
export { type Maze, type MazeProperties } from './maze.ts';
export { OctogonMaze } from './octogon-maze.ts';
export { PentagonMaze } from './pentagon-maze.ts';
export { SquareMaze } from './square-maze.ts';
export { TriangleMaze } from './triangle-maze.ts';
export { WedgeMaze } from './wedge-maze.ts';
export { ZetaMaze } from './zeta-maze.ts';
