import { type Direction, type Kind, type XY } from './maze.ts';

export const directionMatrix: Direction[] = [
  'a',
  'b',
  'c',
  'd',
  'e',
  'f',
  'g',
  'h',
  'i',
  'j',
  'k',
  'l',
  'm',
  'n',
  'o',
  'p',
  'q',
  'r',
  's',
  't',
];

export const pillarMatrix: `${Direction}${Direction}`[] = [
  'ab',
  'bc',
  'cd',
  'de',
  'ea',
  'fg',
  'gh',
  'fi',
  'jk',
  'jf',
  'kl',
  'lm',
  'mn',
  'no',
  'ok',
  'pq',
  'qr',
  'rs',
  'st',
  'tp',
];

export const kindMatrix: number[][] = [
  [0, 1, 2, 3],
  [2, 3, 0, 1],
  [3, 0, 1, 2],
  [1, 2, 3, 0],
  [2, 3, 0, 1],
];

export const sidesMatrix: Record<Kind, number> = {
  0: 5,
  1: 5,
  2: 5,
  3: 5,
};

export const wallMatrix: Record<Direction, boolean>[] = [
  { a: true, b: true, c: true, d: true, e: true },
  { f: true, g: true, h: true, i: true, j: true },
  { k: true, l: true, m: true, n: true, o: true },
  { p: true, q: true, r: true, s: true, t: true },
];
export const oppositeMatrix: Record<Direction, Direction> = {
  a: 'm',
  b: 'j',
  c: 'o',
  d: 'g',
  e: 'r',
  f: 's',
  g: 'd',
  h: 'p',
  i: 'k',
  j: 'b',
  k: 'i',
  l: 't',
  m: 'a',
  n: 'q',
  o: 'c',
  p: 'h',
  q: 'n',
  r: 'e',
  s: 'f',
  t: 'l',
};

export const rightTurnMatrix: Record<Direction, Direction[]> = {
  a: ['l', 'k', 'o', 'n', 'm'],
  b: ['i', 'h', 'g', 'f', 'j'],
  c: ['n', 'm', 'l', 'k', 'o'],
  d: ['f', 'j', 'i', 'h', 'g'],
  e: ['q', 'p', 't', 's', 'r'],
  f: ['r', 'q', 'p', 't', 's'],
  g: ['c', 'b', 'a', 'e', 'd'],
  h: ['t', 's', 'r', 'q', 'p'],
  i: ['o', 'n', 'm', 'l', 'k'],
  j: ['a', 'e', 'd', 'c', 'b'],
  k: ['h', 'g', 'f', 'j', 'i'],
  l: ['s', 'r', 'q', 'p', 't'],
  m: ['e', 'd', 'c', 'b', 'a'],
  n: ['p', 't', 's', 'r', 'q'],
  o: ['b', 'a', 'e', 'd', 'c'],
  p: ['g', 'f', 'j', 'i', 'h'],
  q: ['m', 'l', 'k', 'o', 'n'],
  r: ['d', 'c', 'b', 'a', 'e'],
  s: ['j', 'i', 'h', 'g', 'f'],
  t: ['k', 'o', 'n', 'm', 'l'],
};

export const leftTurnMatrix: Record<Direction, Direction[]> = {
  a: ['n', 'o', 'k', 'l', 'm'],
  b: ['f', 'g', 'h', 'i', 'j'],
  c: ['k', 'l', 'm', 'n', 'o'],
  d: ['h', 'i', 'j', 'f', 'g'],
  e: ['s', 't', 'p', 'q', 'r'],
  f: ['t', 'p', 'q', 'r', 's'],
  g: ['e', 'a', 'b', 'c', 'd'],
  h: ['q', 'r', 's', 't', 'p'],
  i: ['l', 'm', 'n', 'o', 'k'],
  j: ['c', 'd', 'e', 'a', 'b'],
  k: ['j', 'f', 'g', 'h', 'i'],
  l: ['p', 'q', 'r', 's', 't'],
  m: ['b', 'c', 'd', 'e', 'a'],
  n: ['r', 's', 't', 'p', 'q'],
  o: ['d', 'e', 'a', 'b', 'c'],
  p: ['i', 'j', 'f', 'g', 'h'],
  q: ['o', 'k', 'l', 'm', 'n'],
  r: ['a', 'b', 'c', 'd', 'e'],
  s: ['g', 'h', 'i', 'j', 'f'],
  t: ['m', 'n', 'o', 'k', 'l'],
};

export const moveMatrix: Record<Kind, Record<Direction, XY[]>> = {
  0: {
    a: [
      { x: +0, y: -1 },
      { x: +0, y: -1 },
      { x: -1, y: -1 },
      { x: +0, y: -1 },
      { x: -1, y: -1 },
    ],
    b: [
      { x: +1, y: +0 },
      { x: +1, y: +0 },
      { x: +1, y: +0 },
      { x: +1, y: +0 },
      { x: +1, y: +0 },
    ],
    c: [
      { x: +0, y: +1 },
      { x: +1, y: +1 },
      { x: +0, y: +1 },
      { x: +1, y: +1 },
      { x: +0, y: +1 },
    ],
    d: [
      { x: -1, y: +1 },
      { x: +0, y: +1 },
      { x: -1, y: +1 },
      { x: +0, y: +1 },
      { x: -1, y: +1 },
    ],
    e: [
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
    ],
  },
  1: {
    f: [
      { x: +0, y: -1 },
      { x: +0, y: -1 },
      { x: -1, y: -1 },
      { x: +0, y: -1 },
      { x: -1, y: -1 },
    ],
    g: [
      { x: +1, y: -1 },
      { x: +1, y: -1 },
      { x: +0, y: -1 },
      { x: +1, y: -1 },
      { x: +0, y: -1 },
    ],
    h: [
      { x: +0, y: +1 },
      { x: +1, y: +1 },
      { x: +0, y: +1 },
      { x: +1, y: +1 },
      { x: +0, y: +1 },
    ],
    i: [
      { x: -1, y: +1 },
      { x: +0, y: +1 },
      { x: -1, y: +1 },
      { x: +0, y: +1 },
      { x: -1, y: +1 },
    ],
    j: [
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
    ],
  },
  2: {
    k: [
      { x: +1, y: -1 },
      { x: +1, y: -1 },
      { x: +0, y: -1 },
      { x: +1, y: -1 },
      { x: +0, y: -1 },
    ],
    l: [
      { x: +1, y: 0 },
      { x: +1, y: 0 },
      { x: +1, y: 0 },
      { x: +1, y: 0 },
      { x: +1, y: 0 },
    ],
    m: [
      { x: +0, y: +1 },
      { x: +1, y: +1 },
      { x: +0, y: +1 },
      { x: +1, y: +1 },
      { x: +0, y: +1 },
    ],
    n: [
      { x: -1, y: +1 },
      { x: +0, y: +1 },
      { x: -1, y: +1 },
      { x: +0, y: +1 },
      { x: -1, y: +1 },
    ],
    o: [
      { x: +0, y: -1 },
      { x: +0, y: -1 },
      { x: -1, y: -1 },
      { x: +0, y: -1 },
      { x: -1, y: -1 },
    ],
  },
  3: {
    p: [
      { x: +0, y: -1 },
      { x: +0, y: -1 },
      { x: -1, y: -1 },
      { x: +0, y: -1 },
      { x: -1, y: -1 },
    ],
    q: [
      { x: +1, y: -1 },
      { x: +1, y: -1 },
      { x: +0, y: -1 },
      { x: +1, y: -1 },
      { x: +0, y: -1 },
    ],
    r: [
      { x: +1, y: +0 },
      { x: +1, y: +0 },
      { x: +1, y: +0 },
      { x: +1, y: +0 },
      { x: +1, y: +0 },
    ],
    s: [
      { x: +0, y: +1 },
      { x: +1, y: +1 },
      { x: +0, y: +1 },
      { x: +1, y: +1 },
      { x: +0, y: +1 },
    ],
    t: [
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
    ],
  },
};

export const offsetXMatrix = [
  [+0.0, +1.0, +2.5, +4.0],
  [+0.5, +2.0, +3.0, +4.0],
  [+0.0, +1.0, +2.0, +3.5],
  [+0.0, +1.5, +3.0, +4.0],
  [-0.5, +1.0, +2.0, +3.0],
];

export const offsetYMatrix = [
  [+0.0, +0.0, +0.0, -0.5],
  [+1.0, +0.5, +1.0, +1.0],
  [+1.5, +2.0, +2.0, +2.0],
  [+3.0, +3.0, +2.5, +3.0],
  [+4.0, +3.5, +4.0, +4.0],
];

export const edgesMatrix: Record<Kind, Direction[]> = {
  0: ['b', 'c', 'd'],
  1: ['h', 'i', 'j'],
  2: ['l', 'm'],
  3: ['r', 's'],
};

export const pathMatrix: Record<Direction, number> = {
  a: 90,
  b: 0,
  c: 315,
  d: 225,
  e: 180,
  f: 90,
  g: 45,
  h: 315,
  i: 270,
  j: 180,
  k: 90,
  l: 0,
  m: 270,
  n: 225,
  o: 135,
  p: 135,
  q: 45,
  r: 0,
  s: 270,
  t: 180,
};
