/* eslint-disable @typescript-eslint/no-unnecessary-type-conversion */
import { type Matrix } from './maze.ts';

export const matrix: Matrix = {
  // bridge: {
  //   pieces: 1,
  //   layouts: {
  //     0: [
  //       { path: ['a'] },
  //       { path: ['b'] },
  //       { path: ['c'] },
  //       { path: ['d'] },
  //       { path: ['e'] },
  //       { path: ['f'] },
  //       { path: ['g'] },
  //       { path: ['h'] },
  //     ],
  //   },
  // },
  directions: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],
  pillars: ['ab', 'bc', 'cd', 'de', 'ef', 'fg', 'gh', 'ha'],
  wall: {
    0: { a: true, b: true, c: true, d: true, e: true, f: true, g: true, h: true },
  },
  opposite: {
    a: 'e',
    b: 'f',
    c: 'g',
    d: 'h',
    e: 'a',
    f: 'b',
    g: 'c',
    h: 'd',
  },
  rightTurn: {
    a: ['d', 'c', 'b', 'a', 'h', 'g', 'f', 'e'],
    b: ['e', 'd', 'c', 'b', 'a', 'h', 'g', 'f'],
    c: ['f', 'e', 'd', 'c', 'b', 'a', 'h', 'g'],
    d: ['g', 'f', 'e', 'd', 'c', 'b', 'a', 'h'],
    e: ['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a'],
    f: ['a', 'h', 'g', 'f', 'e', 'd', 'c', 'b'],
    g: ['b', 'a', 'h', 'g', 'f', 'e', 'd', 'c'],
    h: ['c', 'b', 'a', 'h', 'g', 'f', 'e', 'd'],
  },
  leftTurn: {
    a: ['f', 'g', 'h', 'a', 'b', 'c', 'd', 'e'],
    b: ['g', 'h', 'a', 'b', 'c', 'd', 'e', 'f'],
    c: ['h', 'a', 'b', 'c', 'd', 'e', 'f', 'g'],
    d: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],
    e: ['b', 'c', 'd', 'e', 'f', 'g', 'h', 'a'],
    f: ['c', 'd', 'e', 'f', 'g', 'h', 'a', 'b'],
    g: ['d', 'e', 'f', 'g', 'h', 'a', 'b', 'c'],
    h: ['e', 'f', 'g', 'h', 'a', 'b', 'c', 'd'],
  },
  straight: {
    a: ['a', 'bh', 'cg', 'df', 'e'],
    b: ['b', 'ac', 'dh', 'eg', 'f'],
    c: ['c', 'bd', 'ae', 'fh', 'g'],
    d: ['d', 'ce', 'bf', 'ag', 'h'],
    e: ['e', 'df', 'cg', 'bh', 'a'],
    f: ['f', 'eg', 'dh', 'cg', 'b'],
    g: ['g', 'fh', 'ea', 'dh', 'c'],
    h: ['h', 'ag', 'bf', 'cg', 'd'],
  },
  move: {
    0: {
      a: { x: +0, y: -1 },
      b: { x: +1, y: -1 },
      c: { x: +1, y: +0 },
      d: { x: +1, y: +1 },
      e: { x: +0, y: +1 },
      f: { x: -1, y: +1 },
      g: { x: -1, y: +0 },
      h: { x: -1, y: -1 },
    },
  },
  preferred: {
    0: ['c', 'd', 'e'],
  },
  angle: {
    a: 90,
    b: 45,
    c: 0,
    d: 315,
    e: 270,
    f: 225,
    g: 180,
    h: 135,
  },
};
