/* eslint-disable @typescript-eslint/no-unnecessary-type-conversion */
import { type Matrix } from './maze.ts';

export const matrix: Matrix = {
  bridge: {
    connect: {
      a: 'e',
      b: 'f',
      c: 'g',
      d: 'h',
      e: 'a',
      f: 'b',
      g: 'c',
      h: 'd',
      i: 'k',
      j: 'l',
      k: 'i',
      l: 'j',
    },
    layouts: {
      0: [
        { path: ['a'] },
        { path: ['b', 'i'], pieces: 2 },
        { path: ['c'] },
        { path: ['d', 'j'], pieces: 2 },
        { path: ['e'] },
        { path: ['f', 'k'], pieces: 2 },
        { path: ['g'] },
        { path: ['h', 'l'], pieces: 2 },
      ],
      1: [{ path: ['i', 'b'] }, { path: ['j', 'd'] }, { path: ['k', 'f'] }, { path: ['l', 'h'] }],
    },
  },
  directions: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l'],
  pillars: ['ab', 'bc', 'cd', 'de', 'ef', 'fg', 'gh', 'ha', 'ij', 'jk', 'kl', 'li'],
  wall: {
    0: { a: true, b: true, c: true, d: true, e: true, f: true, g: true, h: true },
    1: { i: true, j: true, k: true, l: true },
  },
  opposite: {
    direction: {
      a: 'E',
      b: 'K',
      c: 'G',
      d: 'L',
      e: 'A',
      f: 'I',
      g: 'C',
      h: 'J',
      i: 'F',
      j: 'H',
      k: 'B',
      l: 'D',
    },
    facing: {
      A: 'e',
      B: 'k',
      C: 'g',
      D: 'l',
      E: 'a',
      F: 'i',
      G: 'c',
      H: 'j',
      I: 'f',
      J: 'h',
      K: 'b',
      L: 'd',
    },
  },
  rightTurn: {
    A: ['d', 'c', 'b', 'a', 'h', 'g', 'f', 'e'],
    B: ['j', 'i', 'l', 'k'],
    C: ['f', 'e', 'd', 'c', 'b', 'a', 'h', 'g'],
    D: ['k', 'j', 'i', 'l'],
    E: ['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a'],
    F: ['l', 'k', 'j', 'i'],
    G: ['b', 'a', 'h', 'g', 'f', 'e', 'd', 'c'],
    H: ['i', 'l', 'k', 'j'],
    I: ['e', 'd', 'c', 'b', 'a', 'h', 'g', 'f'],
    J: ['g', 'f', 'e', 'd', 'c', 'b', 'a', 'h'],
    K: ['a', 'h', 'g', 'f', 'e', 'd', 'c', 'b'],
    L: ['c', 'b', 'a', 'h', 'g', 'f', 'e', 'd'],
  },
  leftTurn: {
    A: ['f', 'g', 'h', 'a', 'b', 'c', 'd', 'e'],
    B: ['l', 'i', 'j', 'k'],
    C: ['h', 'a', 'b', 'c', 'd', 'e', 'f', 'g'],
    D: ['i', 'j', 'k', 'l'],
    E: ['b', 'c', 'd', 'e', 'f', 'g', 'h', 'a'],
    F: ['j', 'k', 'l', 'i'],
    G: ['d', 'e', 'f', 'g', 'h', 'a', 'b', 'c'],
    H: ['k', 'l', 'i', 'j'],
    I: ['g', 'h', 'a', 'b', 'c', 'd', 'e', 'f'],
    J: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],
    K: ['c', 'd', 'e', 'f', 'g', 'h', 'a', 'b'],
    L: ['e', 'f', 'g', 'h', 'a', 'b', 'c', 'd'],
  },
  straight: {
    A: ['a', 'hb', 'cg', 'df', 'e'],
    B: ['i', 'lj', 'k'],
    C: ['c', 'bd', 'ae', 'hf', 'g'],
    D: ['j', 'ik', 'l'],
    E: ['e', 'df', 'cg', 'bh', 'a'],
    F: ['k', 'lj', 'i'],
    G: ['g', 'fh', 'ae', 'bd', 'c'],
    H: ['l', 'ik', 'j'],
    I: ['b', 'ac', 'hd', 'eg', 'f'],
    J: ['d', 'ce', 'bf', 'ag', 'h'],
    K: ['f', 'eg', 'hd', 'ac', 'b'],
    L: ['h', 'ag', 'bf', 'ce', 'd'],
  },
  move: {
    0: {
      a: { x: +0, y: -1 },
      b: { x: +1, y: -1 },
      c: { x: +2, y: +0 },
      d: { x: +1, y: +0 },
      e: { x: +0, y: +1 },
      f: { x: -1, y: +0 },
      g: { x: -2, y: +0 },
      h: { x: -1, y: -1 },
    },
    1: {
      i: { x: +1, y: +0 },
      j: { x: +1, y: +1 },
      k: { x: -1, y: +1 },
      l: { x: -1, y: +0 },
    },
  },
  preferred: {
    0: ['c', 'd', 'e'],
    1: ['j'],
  },
  angle: {
    a: 270,
    b: 315,
    c: 0,
    d: 45,
    e: 90,
    f: 135,
    g: 180,
    h: 225,
    i: 315,
    j: 45,
    k: 135,
    l: 225,
  },
};
