/* eslint-disable @typescript-eslint/no-unnecessary-type-conversion */
import { type Matrix } from './maze.ts';

const bridge = {
  bridgePieces: 1,
  build: {
    0: {
      a: [['a']],
      b: [['b', 'i']],
      c: [['c']],
      d: [['d', 'j']],
      e: [['e']],
      f: [['f', 'k']],
      g: [['g']],
      h: [['h', 'l']],
    },
    1: {
      i: [['i', 'b']],
      j: [['j', 'd']],
      k: [['k', 'f']],
      l: [['l', 'h']],
    },
  },
};

export const matrix: Matrix = {
  directions: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l'],
  pillars: ['ab', 'bc', 'cd', 'de', 'ef', 'fg', 'gh', 'ha', 'ij', 'jk', 'kl', 'li'],
  wall: {
    0: { a: true, b: true, c: true, d: true, e: true, f: true, g: true, h: true },
    1: { i: true, j: true, k: true, l: true },
  },
  opposite: {
    a: 'e',
    b: 'k',
    c: 'g',
    d: 'l',
    e: 'a',
    f: 'i',
    g: 'c',
    h: 'j',
    i: 'f',
    j: 'h',
    k: 'b',
    l: 'd',
  },
  inverse: {
    a: 'e',
    b: 'f',
    c: 'g',
    d: 'h',
    e: 'a',
    f: 'b',
    g: 'c',
    h: 'd',
    i: 'k',
    j: 'l',
    k: 'i',
    l: 'j',
  },
  rightTurn: {
    a: ['d', 'c', 'b', 'a', 'h', 'g', 'f', 'e'],
    b: ['j', 'i', 'l', 'k'],
    c: ['f', 'e', 'd', 'c', 'b', 'a', 'h', 'g'],
    d: ['k', 'j', 'i', 'l'],
    e: ['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a'],
    f: ['l', 'k', 'j', 'i'],
    g: ['b', 'a', 'h', 'g', 'f', 'e', 'd', 'c'],
    h: ['i', 'l', 'k', 'j'],
    i: ['e', 'd', 'c', 'b', 'a', 'h', 'g', 'f'],
    j: ['g', 'f', 'e', 'd', 'c', 'b', 'a', 'h'],
    k: ['a', 'h', 'g', 'f', 'e', 'd', 'c', 'b'],
    l: ['c', 'b', 'a', 'h', 'g', 'f', 'e', 'd'],
  },
  leftTurn: {
    a: ['f', 'g', 'h', 'a', 'b', 'c', 'd', 'e'],
    b: ['l', 'i', 'j', 'k'],
    c: ['h', 'a', 'b', 'c', 'd', 'e', 'f', 'g'],
    d: ['i', 'j', 'k', 'l'],
    e: ['b', 'c', 'd', 'e', 'f', 'g', 'h', 'a'],
    f: ['j', 'k', 'l', 'i'],
    g: ['d', 'e', 'f', 'g', 'h', 'a', 'b', 'c'],
    h: ['k', 'l', 'i', 'j'],
    i: ['g', 'h', 'a', 'b', 'c', 'd', 'e', 'f'],
    j: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],
    k: ['c', 'd', 'e', 'f', 'g', 'h', 'a', 'b'],
    l: ['e', 'f', 'g', 'h', 'a', 'b', 'c', 'd'],
  },
  straight: {
    a: ['a', 'hb', 'cg', 'df', 'e'],
    b: ['i', 'lj', 'k'],
    c: ['c', 'bd', 'ae', 'hf', 'g'],
    d: ['j', 'ik', 'l'],
    e: ['e', 'df', 'cg', 'bh', 'a'],
    f: ['k', 'lj', 'i'],
    g: ['g', 'fh', 'ae', 'bd', 'c'],
    h: ['l', 'ik', 'j'],
    i: ['b', 'ac', 'hd', 'eg', 'f'],
    j: ['d', 'ce', 'bf', 'ag', 'h'],
    k: ['f', 'eg', 'hd', 'ac', 'b'],
    l: ['h', 'ag', 'bf', 'ce', 'd'],
  },
  move: {
    0: {
      a: { x: +0, y: -1 },
      b: { x: +1, y: -1 },
      c: { x: +2, y: +0 },
      d: { x: +1, y: +0 },
      e: { x: +0, y: +1 },
      f: { x: -1, y: +0 },
      g: { x: -2, y: +0 },
      h: { x: -1, y: -1 },
    },
    1: {
      i: { x: +1, y: +0 },
      j: { x: +1, y: +1 },
      k: { x: -1, y: +1 },
      l: { x: -1, y: +0 },
    },
  },
  preferred: {
    0: ['c', 'd', 'e'],
    1: ['j'],
  },
  angle: {
    a: 90,
    b: 45,
    c: 0,
    d: 315,
    e: 270,
    f: 225,
    g: 180,
    h: 135,
    i: 45,
    j: 315,
    k: 225,
    l: 135,
  },
};
