/* eslint-disable @typescript-eslint/no-unnecessary-type-conversion */
import { type Matrix } from './maze.ts';

const bridge = {
  bridgePieces: 1,
  build: {
    0: {
      a: [
        ['a', 'g', 'j', 'd'], // ^
        ['a', 'g', 'k'], // /
        ['a', 'i', 'd'], // \
      ],
      b: [
        ['b', 'e', 'g', 'k'],
        ['b', 'f', 'l', 'h'],
        ['b', 'e', 'h'],
        ['b', 'f', 'c'],
      ],
      c: [
        ['c', 'l', 'i', 'd'],
        ['c', 'l', 'h'],
        ['c', 'j', 'd'],
      ],
    },
    1: '=0',
  },
};

export const matrix: Matrix = {
  directions: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l'],
  pillars: ['ab', 'bc', 'ca', 'de', 'ef', 'fd', 'gh', 'hi', 'ig', 'jk', 'kl', 'lj'],
  wall: {
    0: { a: true, b: true, c: true },
    1: { d: true, e: true, f: true },
    2: { g: true, h: true, i: true },
    3: { j: true, k: true, l: true },
  },
  opposite: {
    a: 'h',
    b: 'd',
    c: 'k',
    d: 'b',
    e: 'i',
    f: 'j',
    g: 'l',
    h: 'a',
    i: 'e',
    j: 'f',
    k: 'c',
    l: 'g',
  },
  inverse: {
    a: 'h',
    b: 'd',
    c: 'k',
    d: 'b',
    e: 'i',
    f: 'j',
    g: 'l',
    h: 'a',
    i: 'e',
    j: 'f',
    k: 'c',
    l: 'g',
  },
  rightTurn: {
    a: ['g', 'i', 'h'],
    b: ['f', 'e', 'd'],
    c: ['j', 'l', 'k'],
    d: ['a', 'c', 'b'],
    e: ['h', 'g', 'i'],
    f: ['l', 'k', 'j'],
    g: ['k', 'j', 'l'],
    h: ['c', 'b', 'a'],
    i: ['d', 'f', 'e'],
    j: ['e', 'd', 'f'],
    k: ['b', 'a', 'c'],
    l: ['i', 'h', 'g'],
  },
  leftTurn: {
    a: ['i', 'g', 'h'],
    b: ['e', 'f', 'd'],
    c: ['l', 'j', 'k'],
    d: ['c', 'a', 'b'],
    e: ['g', 'h', 'i'],
    f: ['k', 'l', 'j'],
    g: ['j', 'k', 'l'],
    h: ['b', 'c', 'a'],
    i: ['f', 'd', 'e'],
    j: ['d', 'e', 'f'],
    k: ['a', 'b', 'c'],
    l: ['h', 'i', 'g'],
  },
  straight: {
    a: ['gi', 'h'],
    b: ['fe', 'd'],
    c: ['jl', 'k'],
    d: ['ac', 'b'],
    e: ['hg', 'i'],
    f: ['kl', 'j'],
    g: ['kj', 'l'],
    h: ['bc', 'a'],
    i: ['df', 'e'],
    j: ['ed', 'f'],
    k: ['ba', 'c'],
    l: ['hi', 'g'],
  },
  move: {
    0: {
      a: { x: +0, y: -1 },
      b: { x: +1, y: +0 },
      c: { x: -1, y: +0 },
    },
    1: {
      d: { x: -1, y: +0 },
      e: { x: +1, y: +0 },
      f: { x: +0, y: +1 },
    },
    2: {
      g: { x: +1, y: +0 },
      h: { x: +0, y: +1 },
      i: { x: -1, y: +0 },
    },
    3: {
      j: { x: +0, y: -1 },
      k: { x: +1, y: +0 },
      l: { x: -1, y: +0 },
    },
  },
  preferred: {
    0: ['b'],
    1: ['e', 'f'],
    2: ['g', 'h'],
    3: ['k'],
  },
  angle: {
    a: 90,
    b: 315,
    c: 180,
    d: 135,
    e: 0,
    f: 270,
    g: 45,
    h: 270,
    i: 180,
    j: 90,
    k: 0,
    l: 225,
  },
};
