/*
 *  This file is automatically generated by css-module-type-definitions
 */

export type Keys = 'watermark';
export type css = { [key in Keys]: string };

declare const css: css;
export default css;
