import { type Direction, type Kind, type Pillar, type XY } from './maze.js';

export const directionMatrix: Direction[] = [
  'a',
  'b',
  'c',
  'd',
  'e',
  'f',
  'g',
  'h',
  'i',
  'j',
  'k',
  'l',
];
export const pillarMatrix: Pillar[] = [
  'ab',
  'bc',
  'cd',
  'de',
  'ef',
  'fg',
  'gh',
  'ha',
  'ij',
  'jk',
  'kl',
  'li',
];

export const sidesMatrix: Record<Kind, number> = {
  0: 4,
  1: 4,
  2: 4,
  3: 4,
  4: 4,
  5: 4,
};

export const wallMatrix: Record<Kind, Record<Direction, boolean>> = {
  0: { a: true, b: true, c: true, d: true },
  1: { e: true, f: true, g: true, h: true },
  2: { i: true, j: true, k: true, l: true },
  3: { a: true, b: true, c: true, d: true },
  4: { e: true, f: true, g: true, h: true },
  5: { i: true, j: true, k: true, l: true },
};

export const oppositeMatrix: Record<Direction, Direction> = {
  a: 'g',
  b: 'l',
  c: 'e',
  d: 'j',
  e: 'c',
  f: 'i',
  g: 'a',
  h: 'k',
  i: 'f',
  j: 'd',
  k: 'h',
  l: 'b',
};

export const rightTurnMatrix: Record<Direction, Direction[]> = {
  a: ['f', 'e', 'h', 'g'],
  b: ['k', 'j', 'i', 'l'],
  c: ['f', 'g', 'h', 'e'],
  d: ['i', 'l', 'k', 'j'],
  e: ['b', 'a', 'd', 'c'],
  f: ['l', 'k', 'j', 'i'],
  g: ['d', 'c', 'b', 'a'],
  h: ['j', 'i', 'l', 'k'],
  i: ['e', 'h', 'g', 'f'],
  j: ['c', 'b', 'a', 'd'],
  k: ['g', 'f', 'e', 'h'],
  l: ['a', 'd', 'c', 'b'],
};

export const leftTurnMatrix: Record<Direction, Direction[]> = {
  a: ['h', 'e', 'f', 'g'],
  b: ['i', 'j', 'k', 'l'],
  c: ['h', 'g', 'f', 'e'],
  d: ['k', 'l', 'i', 'j'],
  e: ['d', 'a', 'b', 'c'],
  f: ['j', 'k', 'l', 'i'],
  g: ['b', 'c', 'd', 'a'],
  h: ['l', 'i', 'j', 'k'],
  i: ['g', 'h', 'e', 'f'],
  j: ['a', 'b', 'c', 'd'],
  k: ['e', 'f', 'g', 'h'],
  l: ['c', 'd', 'a', 'b'],
};

export const moveMatrix: Record<Kind, Record<Direction, XY[]>> = {
  0: {
    a: [
      { x: +1, y: +0 },
      { x: +1, y: +0 },
      { x: +1, y: +0 },
      { x: +1, y: +0 },
      { x: +1, y: +0 },
      { x: +1, y: +0 },
      { x: +1, y: +0 },
      { x: +1, y: +0 },
    ],
    b: [
      { x: +2, y: +0 },
      { x: +2, y: +0 },
      { x: +2, y: +0 },
      { x: +2, y: +0 },
      { x: +2, y: +0 },
      { x: +2, y: +0 },
      { x: +2, y: +0 },
      { x: +2, y: +0 },
    ],
    c: [
      { x: +1, y: +1 },
      { x: -2, y: +1 },
      { x: +1, y: +1 },
      { x: +1, y: +1 },
      { x: -2, y: +1 },
      { x: +1, y: +1 },
      { x: +1, y: +1 },
      { x: +1, y: +1 },
    ],
    d: [
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +1 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
    ],
  },
  1: {
    e: [
      { x: -1, y: -1 },
      { x: -1, y: -1 },
      { x: +2, y: -1 },
      { x: -1, y: -1 },
      { x: -1, y: -1 },
      { x: +1, y: -1 },
      { x: -1, y: -1 },
      { x: -1, y: -1 },
    ],
    f: [
      { x: +1, y: +0 },
      { x: +1, y: +0 },
      { x: +1, y: +0 },
      { x: +1, y: +0 },
      { x: +1, y: +0 },
      { x: +1, y: +0 },
      { x: +1, y: +0 },
      { x: +1, y: +0 },
    ],
    g: [
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
    ],
    h: [
      { x: -2, y: +0 },
      { x: -2, y: -1 },
      { x: +1, y: -1 },
      { x: -2, y: -1 },
      { x: +1, y: -1 },
      { x: -1, y: -1 },
      { x: -2, y: -1 },
      { x: -2, y: -1 },
    ],
  },
  2: {
    i: [
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
      { x: -1, y: +0 },
    ],
    j: [
      { x: +1, y: +0 },
      { x: +1, y: -1 },
      { x: +4, y: -1 },
      { x: +4, y: -1 },
      { x: +1, y: +0 },
      { x: +1, y: +0 },
      { x: +1, y: +0 },
      { x: +1, y: +0 },
    ],
    k: [
      { x: +2, y: +1 },
      { x: +2, y: +0 },
      { x: +2, y: +0 },
      { x: +2, y: +1 },
      { x: +1, y: +1 },
      { x: +2, y: +0 },
      { x: +2, y: +0 },
      { x: +2, y: +0 },
    ],
    l: [
      { x: -2, y: +0 },
      { x: -2, y: +0 },
      { x: -2, y: +0 },
      { x: -2, y: +0 },
      { x: -2, y: +0 },
      { x: -2, y: +0 },
      { x: -2, y: +0 },
      { x: -2, y: +0 },
    ],
  },
};

export const edgesMatrix: Record<Kind, Direction[]> = {
  0: ['b', 'c'],
  1: ['f', 'g'],
  2: ['i', 'j'],
  3: ['b', 'c'],
  4: ['f', 'g'],
  5: ['i', 'j'],
};

export const pathMatrix: Record<Direction, number> = {
  a: 90,
  b: 0,
  c: 270,
  d: 180,
  e: 45,
  f: 0,
  g: 225,
  h: 180,
  i: 90,
  j: 45,
  k: 270,
  l: 225,
};
