/* eslint-disable @typescript-eslint/no-unnecessary-type-conversion */
import { type Matrix } from '../matrix.ts';

export const matrix: Matrix = {
  bridge: {
    connect: {},
    layouts: {
      0: [
        { path: ['a', 'e'], rear: ['g', 'c'], connect: { b: 'd', d: 'b', f: 'h', h: 'f' } },
        { path: ['b', 'j'], rear: ['l', 'd'], connect: { a: 'c', d: 'a', i: 'k', k: 'i' } },
        { path: ['c', 'g'], rear: ['e', 'a'], connect: { b: 'd', d: 'b', f: 'h', h: 'f' } },
        { path: ['d', 'l'], rear: ['j', 'b'], connect: { a: 'c', d: 'a', i: 'k', k: 'i' } },
      ],
      1: [
        { path: ['e', 'a'], rear: ['c', 'g'], connect: { b: 'd', d: 'b', f: 'h', h: 'f' } },
        { path: ['f', 'k'], rear: ['l', 'h'], connect: { a: 'c', c: 'a', e: 'g', g: 'e' } },
        { path: ['g', 'c'], rear: ['e', 'a'], connect: { b: 'd', d: 'b', f: 'h', h: 'f' } },
        { path: ['h', 'l'], rear: ['k', 'f'], connect: { a: 'c', c: 'a', e: 'g', g: 'e' } },
      ],
      2: [
        { path: ['i', 'h'], rear: ['f', 'k'], connect: { e: 'g', g: 'e', j: 'l', k: 'j' } },
        { path: ['j', 'b'], rear: ['d', 'l'], connect: { a: 'c', c: 'a', i: 'k', k: 'i' } },
        { path: ['k', 'f'], rear: ['h', 'i'], connect: { e: 'g', g: 'e', j: 'l', k: 'j' } },
        { path: ['l', 'd'], rear: ['b', 'g'], connect: { a: 'c', c: 'a', e: 'g', g: 'e' } },
      ],
    },
  },
  directions: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l'],
  pillars: ['ab', 'bc', 'cd', 'da', 'ef', 'fg', 'gh', 'he', 'ij', 'jk', 'kl', 'li'],
  wall: {
    0: { a: true, b: true, c: true, d: true },
    1: { e: true, f: true, g: true, h: true },
    2: { i: true, j: true, k: true, l: true },
    3: { a: true, b: true, c: true, d: true },
    4: { e: true, f: true, g: true, h: true },
    5: { i: true, j: true, k: true, l: true },
  },
  opposite: {
    direction: {
      a: 'G',
      b: 'L',
      c: 'E',
      d: 'J',
      e: 'C',
      f: 'I',
      g: 'A',
      h: 'K',
      i: 'F',
      j: 'D',
      k: 'H',
      l: 'B',
    },
    facing: {
      A: 'g',
      B: 'l',
      C: 'e',
      D: 'j',
      E: 'c',
      F: 'i',
      G: 'a',
      H: 'k',
      I: 'f',
      J: 'd',
      K: 'h',
      L: 'b',
    },
  },
  rightTurn: {
    A: ['f', 'e', 'h', 'g'],
    B: ['k', 'j', 'i', 'l'],
    C: ['h', 'g', 'f', 'e'],
    D: ['i', 'l', 'k', 'j'],
    E: ['b', 'a', 'd', 'c'],
    F: ['l', 'k', 'j', 'i'],
    G: ['d', 'c', 'b', 'a'],
    H: ['j', 'i', 'l', 'k'],
    I: ['e', 'h', 'g', 'f'],
    J: ['c', 'b', 'a', 'd'],
    K: ['g', 'f', 'e', 'h'],
    L: ['a', 'd', 'c', 'b'],
  },
  leftTurn: {
    A: ['h', 'e', 'f', 'g'],
    B: ['i', 'j', 'k', 'l'],
    C: ['f', 'g', 'h', 'e'],
    D: ['k', 'l', 'i', 'j'],
    E: ['d', 'a', 'b', 'c'],
    F: ['j', 'k', 'l', 'i'],
    G: ['b', 'c', 'd', 'a'],
    H: ['l', 'i', 'j', 'k'],
    I: ['g', 'h', 'e', 'f'],
    J: ['a', 'b', 'c', 'd'],
    K: ['e', 'f', 'g', 'h'],
    L: ['c', 'd', 'a', 'b'],
  },
  straight: {
    A: ['e', 'hf', 'g'],
    B: ['j', 'ki', 'l'],
    C: ['g', 'fh', 'e'],
    D: ['l', 'ki', 'j'],
    E: ['a', 'bd', 'c'],
    F: ['k', 'jl', 'i'],
    G: ['c', 'db', 'a'],
    H: ['i', 'lj', 'k'],
    I: ['h', 'eg', 'f'],
    J: ['b', 'ac', 'd'],
    K: ['f', 'eg', 'h'],
    L: ['d', 'ac', 'b'],
  },
  move: {
    0: {
      a: { x: +1, y: +0 },
      b: { x: +2, y: +0 },
      c: { x: -2, y: +1 },
      d: { x: -1, y: +0 },
    },
    1: {
      e: { x: -1, y: -1 },
      f: { x: +1, y: +0 },
      g: { x: -1, y: +0 },
      h: { x: -2, y: -1 },
    },
    2: {
      i: { x: -1, y: +0 },
      j: { x: +1, y: +0 },
      k: { x: -1, y: +1 },
      l: { x: -2, y: +0 },
    },
    3: {
      a: { x: +1, y: +0 },
      b: { x: +2, y: +0 },
      c: { x: +1, y: +1 },
      d: { x: -1, y: +0 },
    },
    4: {
      e: { x: +2, y: -1 },
      f: { x: +1, y: +0 },
      g: { x: -1, y: +0 },
      h: { x: +1, y: -1 },
    },
    5: {
      i: { x: -1, y: +0 },
      j: { x: +1, y: +0 },
      k: { x: +2, y: +1 },
      l: { x: -2, y: +0 },
    },
  },

  preferred: {
    0: ['b', 'c'],
    1: ['f', 'g'],
    2: ['i', 'j'],
    3: ['b', 'c'],
    4: ['f', 'g'],
    5: ['i', 'j'],
    6: ['b', 'c'],
    7: ['f', 'g'],
    8: ['i', 'j'],
  },

  angle: {
    a: 270,
    b: 15,
    c: 90,
    d: 195,
    e: 345,
    f: 15,
    g: 150,
    h: 210,
    i: 270,
    j: 0,
    k: 90,
    l: 150,
  },
};
