/* eslint-disable @typescript-eslint/no-unnecessary-type-conversion */
import { type Matrix } from '../matrix.ts';

export const matrix: Matrix = {
  bridge: {
    pieces: 2,
    connect: { a: 'f', c: 'e', e: 'c', f: 'a', h: 'j', i: 'k', j: 'h', k: 'i' },
    layouts: {
      0: [
        { path: ['a', 'g', 'j', 'd'], rear: ['h', 'l', 'f', 'b'] },
        { path: ['c', 'l', 'i', 'd'], rear: ['k', 'g', 'e', 'b'] },
      ],
      1: [
        { path: ['e', 'g', 'k', 'b'], rear: ['i', 'l', 'c', 'd'] },
        { path: ['f', 'l', 'h', 'b'], rear: ['j', 'g', 'a', 'd'] },
      ],
      2: [
        { path: ['h', 'b', 'f', 'l'], rear: ['a', 'd', 'j', 'g'] },
        { path: ['i', 'd', 'c', 'l'], rear: ['e', 'b', 'k', 'g'] },
      ],
      3: [
        { path: ['j', 'd', 'a', 'g'], rear: ['f', 'b', 'h', 'l'] },
        { path: ['k', 'b', 'e', 'g'], rear: ['c', 'd', 'i', 'l'] },
      ],
    },
  },
  directions: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l'],
  pillars: ['ab', 'bc', 'ca', 'de', 'ef', 'fd', 'gh', 'hi', 'ig', 'jk', 'kl', 'lj'],
  wall: {
    0: { a: true, b: true, c: true },
    1: { d: true, e: true, f: true },
    2: { g: true, h: true, i: true },
    3: { j: true, k: true, l: true },
  },
  opposite: {
    direction: {
      a: 'H',
      b: 'D',
      c: 'K',
      d: 'B',
      e: 'I',
      f: 'J',
      g: 'L',
      h: 'A',
      i: 'E',
      j: 'F',
      k: 'C',
      l: 'G',
    },
    facing: {
      A: 'h',
      B: 'd',
      C: 'k',
      D: 'b',
      E: 'i',
      F: 'j',
      G: 'l',
      H: 'a',
      I: 'e',
      J: 'f',
      K: 'c',
      L: 'g',
    },
  },
  rightTurn: {
    A: ['g', 'i', 'h'],
    B: ['f', 'e', 'd'],
    C: ['j', 'l', 'k'],
    D: ['a', 'c', 'b'],
    E: ['h', 'g', 'i'],
    F: ['l', 'k', 'j'],
    G: ['k', 'j', 'l'],
    H: ['c', 'b', 'a'],
    I: ['d', 'f', 'e'],
    J: ['e', 'd', 'f'],
    K: ['b', 'a', 'c'],
    L: ['i', 'h', 'g'],
  },
  leftTurn: {
    A: ['i', 'g', 'h'],
    B: ['e', 'f', 'd'],
    C: ['l', 'j', 'k'],
    D: ['c', 'a', 'b'],
    E: ['g', 'h', 'i'],
    F: ['k', 'l', 'j'],
    G: ['j', 'k', 'l'],
    H: ['b', 'c', 'a'],
    I: ['f', 'd', 'e'],
    J: ['d', 'e', 'f'],
    K: ['a', 'b', 'c'],
    L: ['h', 'i', 'g'],
  },
  straight: {
    A: ['gi', 'h'],
    B: ['fe', 'd'],
    C: ['jl', 'k'],
    D: ['ac', 'b'],
    E: ['hg', 'i'],
    F: ['kl', 'j'],
    G: ['kj', 'l'],
    H: ['bc', 'a'],
    I: ['df', 'e'],
    J: ['ed', 'f'],
    K: ['ba', 'c'],
    L: ['hi', 'g'],
  },
  move: {
    0: {
      a: { x: +0, y: -1 },
      b: { x: +1, y: +0 },
      c: { x: -1, y: +0 },
    },
    1: {
      d: { x: -1, y: +0 },
      e: { x: +1, y: +0 },
      f: { x: +0, y: +1 },
    },
    2: {
      g: { x: +1, y: +0 },
      h: { x: +0, y: +1 },
      i: { x: -1, y: +0 },
    },
    3: {
      j: { x: +0, y: -1 },
      k: { x: +1, y: +0 },
      l: { x: -1, y: +0 },
    },
  },
  preferred: {
    0: ['b'],
    1: ['e', 'f'],
    2: ['g', 'h'],
    3: ['k'],
  },
  angle: {
    a: 270,
    b: 55,
    c: 180,
    d: 225,
    e: 0,
    f: 90,
    g: 315,
    h: 90,
    i: 180,
    j: 270,
    k: 0,
    l: 135,
  },
};
