export type Track = {
    contentId:                  string,
    path:                       string,
    modified:                   Date,
    artist:                     string[],
    album:                      string,
    performer:                  string[],
    composer:                   string[],
    conductor:                  string[],
    writer:                     string[],
    genre:                      string[],
    subgenre:                   string[],
    title:                      string,
    subtitle:                   string,
    trackNumber:                number,
    is_compilation:             boolean,
    lyrics:                     string,
    mood:                       string,
    initialKey:                 string,
    discNumber:                 number,
    discsInSet:                 number,
    discTitle:                  string,
    period:                     string,
    year:                       number,
    rating:                     number,
    comments:                   string,
    tags:                       string,
    language:                   string,
    publisher:                  string,
    metadataContentProvider:    string,
    encodedBy:                  string,
    authorUrl:                  string,
    copyright:                  string,
    collectionId:               string,
    collectionGroupId:          string,
    dateReleased:               Date,
    uniqueFileIdentifier:       string,
    beatsPerMinute:             number,
    contentProvider:            string,
    promotionUrl:               string,
    parentalRating:             string,
    parentalRatingReason:       string,
    providerStyle:              string,
    provideRating:              number,
    bitrate:                    number,
    isVbr:                      boolean,
    filesize:                   number,
    duration:                   number,
};

export default Track;

